name: feedreader
version: '2.2+git'
summary: FeedReader is a modern desktop RSS application.
description: |
  FeedReader is a modern desktop application designed to complement existing web-based RSS accounts.
  It combines all the advantages of web based services like synchronisation across all your devices with everything you expect from a modern desktop application. 

icon: data/application-icons/hicolor/64x64/apps/org.gnome.FeedReader.svg

grade: devel
confinement: devmode

apps:
  feedreader:
    command: desktop-launch $SNAP/usr/bin/feedreader
    desktop: $SNAPCRAFT_STAGE/usr/share/applications/org.gnome.FeedReader.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: /snap/feedreader/current/usr/share/glib-2.0/schemas
    plugs: [x11, gsettings, network, opengl, pulseaudio, dbus]

slots:
    # for GtkApplication registration
    own-feedreader:
        interface: dbus
        name: org.gnome.FeedReader
        bus: session
    
parts:

  feedreader:
    after: 
      - desktop-gtk3
    plugin: cmake
    source: .
    configflags: ["-DCMAKE_INSTALL_PREFIX=/usr", "-DCMAKE_INSTALL_LIBDIR=lib", "-DGSETTINGS_COMPILE=OFF"]
    install: | 
       glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas

    stage-packages:
      - libwebkit2gtk-4.0-37
      - libcanberra-gtk3-module

    build-packages:
      - build-essential
      - cmake
      - valac
      - pkg-config
      - gettext
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libjson-glib-dev
      - libwebkit2gtk-4.0-dev
      - libsqlite3-dev
      - libsecret-1-dev
      - libnotify-dev
      - libxml2-dev
      - librest-dev
      - libgee-0.8-dev
      - libcurl4-gnutls-dev
      - libgstreamer-plugins-base1.0-dev
      - libpeas-dev
      - libgoa-1.0-dev
